imagerySource:
    url: https://omar.ossim.io/omar-wfs/wfs
    # Define the metadata fields and their regular expressions
    metadataMap:
        acquisitionDate: '"acquisition_date":"([^"]*)"'
        imageId: '"image_id":"([^"]*)"'
        niirs: '"niirs":([^a-zA-Z]*)'
        sensor: '"sensor_id":"([^"]*)"'
    # Define any required URL params
    requiredParams:
        outputFormat: JSON
        request: GetFeature
        service: WFS
        typeName: omar:raster_entry
        version: 1.1.0
    # Where are the results array located in the response
    resultsKey: features
    # Where is the metadata located in each result
    resultsMetadataKey: properties
    # How the params supplied map to the URL params expected by the service
    urlParamMap:
        # This will be evaluated as code
        filter:
            - |
                params.endDate ? "acquisition_date < '" + params.endDate + "'" : ""
            - |
                params.startDate ? "acquisition_date > '" + params.startDate + "'" : ""
            - |
                params.bbox ? "BBOX(ground_geom," + params.bbox + ")" : ""
            - |
                params.niirs ? "niirs > " + params.niirs : ""
            - |
                params.sensors ? "(sensor_id LIKE '%" + params.sensors.split( "," ).join( "%' OR sensor_id LIKE'%" ) + "%')" : ""
        # This will be mapped
        maxFeatures: maxFeatures

server:
    contextPath: /omar-reachback

---
grails:
    profile: web
    codegen:
        defaultPackage: omar.reachback
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
